version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "testpass12345"
      MYSQL_DATABASE: redditclone
    ports:
      - '3306:3306'
    volumes:
      - './_sql/:/docker-entrypoint-initdb.d/'
  
  mongodb:
    image: 'mongo'
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=coursera
    ports:
      - '27017-27019:27017-27019'